# Generated by Django 2.0.7 on 2019-07-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=200)),
                ('test_time', models.IntegerField(default=0)),
                ('error_time', models.IntegerField(default=0)),
            ],
        ),
    ]
