# Generated by Django 2.2.3 on 2019-07-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogery',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='availble',
            new_name='available',
        ),
    ]
    atomic = False
